### ISSUE TITLE
F# plugin never turns green

### ISSUE THREAD

**Issue by misaxi** [BayardRock/FsBeaker#2]
Followed the instruction to installed the plugin. I can see the F# in the plugin manager. After I click it, it stays yellow forever.

![image](https://cloud.githubusercontent.com/assets/767799/6680607/e2823172-ccad-11e4-9785-0aec699c3aa6.png)

console output

```
Running: python "C:\Users\me\Documents\Toolbox\beaker-notebook-v1.1.2-2-gb1a7d5f-windows/config/plugins/eval/fsharp/fsharpPlugin" 8804
looking on stdout found:Successfully started server
Acknowledge FSharp plugin started
Done starting FSharp
FSharp-stdout>[I] 2015-03-17T02:58:44.1576793Z: started listener in: started in 17.993800 ms: 127.0.0.1:8804 [Suave.Tcp.tcp_ip_server]
```

**Comment by eadgbear** [comment]
Looking at some of the traces there's an error that occurs during some sort of channel communication. I can't really diagnose it more than that but it's quite clearly not working.

**Comment by prosconi** [comment]
Oops, sorry I missed this issue.

@misaxi Have you tried latest beaker?

@slyons What version of Beaker and OS are you using?

Also, could be a Javascript problem, any errors in the Javascript console?

**Comment by eadgbear** [comment]
I managed to fish out a stack trace for you. Beaker 1.2.1 on Windows. Here's some of the headers and the response.

```
code:let beaker = new NamespaceClient("jHEmZG")
URL: http://127.0.0.1:8801/7dc8ced/fsharp.128517527521/fsharp/evaluate
Response Code: 500

Stream ended unexpectedly

System.Exception: Stream ended unexpectedly at       FsBeaker.Kernel.ConsoleKernelClient.Execute(ExecuteRequest req) at   FsBeaker.Server.evaluate@102-2.Invoke(String code) at     Microsoft.FSharp.Core.FSharpFunc`2.InvokeFast[V](FSharpFunc`2 func, T arg1, TResult arg2) at     Microsoft.FSharp.Control.AsyncBuilderImpl.args@797-1.Invoke(a a)
```

**Comment by prosconi** [comment]
What happens if you run `FsBeaker.Kernel.exe` manually with no arguments?

**Comment by eadgbear** [comment]
So after unblocking the DLLs the kernel.exe runs but just has a blank output, nothing happens after starting the program. 

That being said, it now works. I'll share the powershell snippet I used to fix it for me:

```
cd FsBeaker-Release-0.3.2-alpha
Get-ChildItem -recurse | Unblock-File
```

**Comment by prosconi** [comment]
I will update the README

**Comment by prosconi** [comment]
Oh, it was already in the README. I keep forget about unblocking.
