### ISSUE TITLE
Failed to create shell

### ISSUE THREAD

**Issue by aolney** [BayardRock/FsBeaker#4]
I've built Beaker from source; previously the f# plugin worked.

Now however it fails as shown in the following image 

![fsharp1](https://cloud.githubusercontent.com/assets/4432084/8610161/4543bdd8-2674-11e5-8bf8-25b6cadd332e.png)

The zip was unblocked before extraction. I'm using commit 0c4bf1ff3c97522fc4d680ec8095977f2d6431f9 of Beaker.

I'm guessing that the GET/POST URLs might have changed; I noticed that "/rest" is now included, but adding that to the f# plugin .js file didn't seem to help.

Happy to raise this with the Beaker folks but thought I'd try here first.

**Comment by prosconi** [comment]
They updated the URL paths a little bit.

**Comment by aolney** [comment]
I built from your changes and can confirm that the plugin loads and that intellisense works.

However,  `let x = 3` fails with silent/blank output. Referencing the .NET libraries with `System.Console.Writeline("hi")` also fails with output that displays a timer that never returns.

Here is the log from that session

> Evaluation ERR: Evaluation STD: val it : unit = ()
> val it : unit = ()
> Stack trace:Stream ended unexpectedlyExceptionStream ended unexpectedly
>    at FsBeaker.Kernel.ConsoleKernel.loop[a]()
>    at FsBeaker.Kernel.ConsoleKernel.start[a]()
>    at Program.main(String[] _arg1)
> Evaluation ERR: Evaluation STD: 
> val x : int = 3
> 
> Stack trace:Stream ended unexpectedlyExceptionStream ended unexpectedly
>    at FsBeaker.Kernel.ConsoleKernel.loop[a]()
>    at FsBeaker.Kernel.ConsoleKernel.start[a]()
>    at Program.main(String[] _arg1)
> Evaluation ERR: Evaluation STD: val it : unit = ()
> val it : unit = ()
> Stack trace:Stream ended unexpectedlyExceptionStream ended unexpectedly
>    at FsBeaker.Kernel.ConsoleKernel.loop[a]()
>    at FsBeaker.Kernel.ConsoleKernel.start[a]()
>    at Program.main(String[] _arg1)
> Evaluation ERR: Evaluation STD: 
> val beaker : NamespaceClient
> 
> Stack trace:Stream ended unexpectedlyExceptionStream ended unexpectedly
>    at FsBeaker.Kernel.ConsoleKernel.loop[a]()
>    at FsBeaker.Kernel.ConsoleKernel.start[a]()
>    at Program.main(String[] _arg1)

I took a look at the R plugin since your last post suggested that plugin calls had changed since December. It looks like the `evaluate` function has three arguments instead of two, with the addition being `refreshObj`

```
evaluate: function(code, modelOutput, refreshObj) {
```

There are also a cancel function and a status update function. I looked at commits from December, and there was also a 3rd argument there, so this may be a bit of a red herring. 

In a nutshell, it's not really clear to me why this isn't working, if I compare the fsharp.js file to the js files for other plugins. This makes me wonder if the problem is on the fsharp server side. 

I compiled with VS 2013 using "Build All" and then ran the build.cmd with no arguments. Although this build the .zip in \release, it did give me two warnings "Found conflicts between different versions of the same dependent assembly" ostensibly b/c I have vs2015-pre installed and it failed when it got to the GenerateHelp target with "FS0192: internal error: null: convTypeRefAux" which may be related to this: https://github.com/Microsoft/visualfsharp/issues/270

However I assume at this stage in the build that the error is not a problem because the plugin has been built. Not so sure about the warnings. 

Could you confirm that the test cases above work for your build?

**Comment by prosconi** [comment]
For something to be displayed `it` needs to be returned. If you do this

``` fsharp
let x = 3
x
```

Then 3 should be displayed.

However, it should not crash when writing to console.

**Comment by aolney** [comment]
My apologies, you are quite right. 

Additional testing shows that crashing when writing to the console is the exception rather than the rule.

Various .NET libraries seem to be working fine (from IO and Collections namespaces).

There are plenty of workarounds for `Writeline()` , so the crash there doesn't really affect me.

Thanks for the great plugin :-)
