### ISSUE TITLE
Building on Linux

### ISSUE THREAD

**Issue by aolney** [BayardRock/FsBeaker#5]
Build.sh seemed to have unresolved dependency errors that were solved by building the solution in Monodevelop. After that, build.sh would fail on the tests. Commenting out the tests in build.fsx resulted in a complete build using build.sh.

**Comment by aolney** [comment]
But that kernel seems to throw errors. After some rooting around, I made the following changes to run FsBeaker on the docker image 1.5.2

In Kernel.fs, change the process start to be mono aware:

```
let procStart = ProcessStartInfo()
        match Environment.OSVersion.Platform with
        | PlatformID.MacOSX | PlatformID.Unix ->
            //Console.WriteLine("Kernel starting with Mono")
            procStart.FileName <- "mono"
            procStart.Arguments <- "FsBeaker.Kernel.exe"
        | _ -> procStart.FileName <- "FsBeaker.Kernel.exe"
```

Remove all reference to FSharp.Data.TypeProviders.dll in Include.fsx and in references -- it can't be found. Not sure of what side effects this might have but things compile.

With these done, I could at least run the first simple test, `[1..1000]`

Putting this on the docker image shows that I have a working kernel, but I can't get the plugin to get through the entire initialization process. It looks like fsharp.js has an init that calls evaluate with 

`var initCode = "let beaker = new NamespaceClient(\"" + bkHelper.getSessionId() + "\")";`

This is what appears to fail and gives a "Stream ended unexpectedly" message. It looks like perhaps during `readBlock`there is a `readline` that returns `null`. That triggers the message.

What is the logic behind aborting when a `null` is read? Wouldn't it make sense to return what has been read up to that point, i.e. only abort when nothing can be read and otherwise return with what has been read?

**Comment by prosconi** [comment]
@aolney Here is how fsbeaker works. Beaker spins up an instance of FsBeaker web service. Beaker then requests that new instances of FsBeaker.Kernel.exe be spun up.

The way FsBeaker and FsBeaker.Kernel.exe communicate is through stdin and stdout. The error message you receive is when the program expected to receive messages back from FsBeaker.Kernel.exe but the executable had already exited. There is probably something that is causing FsBeaker.Kernel.exe to crash.

**Comment by aolney** [comment]
I followed up by writing a unit test for the line of code in question,

```
    let testNamespace(client: ConsoleKernelClient) =
        let code = "let beaker = new NamespaceClient(\"hi\")\nbeaker";
        let result = client.Execute(code)
        //System.Console.Error.WriteLine( result.Result.Data.ToString() )
        Assert.AreEqual(ExecuteReponseStatus.OK, result.Status)
        Assert.AreEqual("text/plain", result.Result.ContentType)    
```

The unit test runs fine, which makes me think this is something on the Beaker side.

Here is the console output (from Chrome) for the error. Any thoughts would be appreciated.

```
beakerVendor.js:21227 POST https://127.0.0.1:8800/6e6bdd3/fsharp.916803482512/fsharp/evaluate 500 (Internal Server Error)
send @ beakerVendor.js:21227
jQuery.extend.ajax @ beakerVendor.js:20683
FSharp.evaluate @ fsharp.js:66
cb @ fsharp.js:191
(anonymous function) @ beakerVendor.js:50306
processQueue @ beakerVendor.js:54801
(anonymous function) @ beakerVendor.js:54817
Scope.$eval @ beakerVendor.js:56045
Scope.$digest @ beakerVendor.js:55856
Scope.$apply @ beakerVendor.js:56153
done @ beakerVendor.js:50602
completeRequest @ beakerVendor.js:50800
requestLoaded @ beakerVendor.js:50741
```

**Comment by aolney** [comment]
Running `ps aux` I can confirm that FsBeaker.Kernel.exe is not running after this error message. Only FsBeaker.exe is running.

Before the call to evaluate, the following calls are made successfully:
- https://127.0.0.1:8800/6e6bdd3/beaker/rest/plugin-services/FSharp?command=fsharp%2FfsharpPlugin&recordOutput=true&startedIndicator=Successfully+started+server&waitfor=Successfully+started+server
- getShell
- setShellOptions

Do you have any additional suggestions for tracking this down? Perhaps somewhere I could add an error message or log I could look at?

**Comment by prosconi** [comment]
My guess is it is loading the wrong FSharp.Core. Ensure that all **.exe.config** files are copied. FsBeaker.Kernel.exe also tries to log to **log.txt** if there is an exception that can be caught.

**Comment by aolney** [comment]
The configs look right to me

```
        <assemblyIdentity name="FSharp.Core" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.3.1.0" newVersion="4.3.1.0" />
```

There are only 2 parts in the config that seem suspicious, but I'm not sure they're causing the error
- The supported runtime has sku ".NETFramework"
- FSharp.Core has some redirects following the one above. I'd assume they'd never be used.

Will follow up on logging

**Comment by aolney** [comment]
I cleaned up the exe.config but didn't see a difference. Also got logging inserted in a few places but haven't figured out the cause yet.

Should I expect FsBeaker.Kernel.exe to show up in `ps aux`? I've been stepping through fsharp.js to see if I can find where it dies but it never shows up anywhere.

**Comment by aolney** [comment]
Some new thoughts
- In `KernelInternals.readBlock` I added code to track how long the read was blocking. When I run on the server it's only blocking for 15 millis (not blocking at all). I see similar behavior when I run in Monodevelop's Application Output window. When I run in the external console window in MD, it works fine (blocks) and when I run in gnome-terminal from the command line it blocks fine.
- It appears there are some known differences in embedding fsi.exe in Windows vs Linux. However the fact that it is working on the command line (both on my machine and in the docker image where Beaker is) but not blocking when called from Beaker is puzzling.

**Comment by aolney** [comment]
I believe your initial guess that FsBeaker.Kernel.exe is immediately dying is correct. I was unable to observe this until I used batch-level top at 100th second intervals `top -d .01 -b -c > ~/top.txt`

As shown below, PID 140 is the initial plugin. At some point, PID 152 begins, and I guess "replaces" FsBeaker.exe in that process with FsBeaker.Kernel.exe. Then it immediately dies and PID 152 goes away.

```
  140 beaker    20   0  550732  28944  18436 S  93.7  0.2   0:00.18 mono ./lib/FsBeaker.exe 8804
  140 beaker    20   0  550872  30992  19656 S  94.7  0.2   0:00.19 mono ./lib/FsBeaker.exe 8804
  152 beaker    20   0  550872  11764     24 R   0.0  0.1   0:00.00 mono ./lib/FsBeaker.exe 8804
  140 beaker    20   0  550872  31712  19764 S  94.3  0.2   0:00.20 mono ./lib/FsBeaker.exe 8804
  152 beaker    20   0  550872  11764     24 R  94.3  0.1   0:00.01 mono ./lib/FsBeaker.exe 8804
  140 beaker    20   0  551432  32624  20324 S  94.3  0.2   0:00.21 mono ./lib/FsBeaker.exe 8804
  152 beaker    20   0  550872  11764     24 R   0.0  0.1   0:00.01 mono ./lib/FsBeaker.exe 8804
  152 beaker    20   0  550872  11764     24 R 100.0  0.1   0:00.03 mono ./lib/FsBeaker.exe 8804
  140 beaker    20   0  552364  34232  21104 S  94.5  0.2   0:00.22 mono ./lib/FsBeaker.exe 8804
  140 beaker    20   0  555512  34724  21512 S  94.7  0.2   0:00.23 mono ./lib/FsBeaker.exe 8804
  152 beaker    20   0  550872  11764     24 R  94.7  0.1   0:00.04 mono ./lib/FsBeaker.exe 8804
  140 beaker    20   0  555640  36268  22612 S  95.0  0.2   0:00.24 mono ./lib/FsBeaker.exe 8804
  152 beaker    20   0  550872  11764     24 R  95.0  0.1   0:00.05 mono ./lib/FsBeaker.exe 8804
  140 beaker    20   0  555640  36496  22612 S  95.0  0.2   0:00.25 mono ./lib/FsBeaker.exe 8804
  152 beaker    20   0  550872  11764     24 R  95.0  0.1   0:00.06 mono ./lib/FsBeaker.exe 8804
  152 beaker    20   0  550872  11764     24 R 100.0  0.1   0:00.08 mono ./lib/FsBeaker.exe 8804
  140 beaker    20   0  555704  37004  22612 S  94.1  0.2   0:00.26 mono ./lib/FsBeaker.exe 8804
  140 beaker    20   0  555704  37568  22620 S  95.1  0.2   0:00.27 mono ./lib/FsBeaker.exe 8804
  152 beaker    20   0  550872  11764     24 R   0.0  0.1   0:00.08 mono ./lib/FsBeaker.exe 8804
  140 beaker    20   0  555768  37828  22620 S 187.2  0.2   0:00.29 mono ./lib/FsBeaker.exe 8804
  152 beaker    20   0  550872  11764     24 R  93.6  0.1   0:00.09 mono ./lib/FsBeaker.exe 8804
  152 beaker    20   0   64592   6036   5364 R 189.5  0.0   0:00.11 /usr/bin/mono FsBeaker.Kernel.exe
  140 beaker    20   0  555768  37828  22620 S   0.0  0.2   0:00.29 mono ./lib/FsBeaker.exe 8804
  140 beaker    20   0  555768  38440  22688 S  93.9  0.2   0:00.30 mono ./lib/FsBeaker.exe 8804
  140 beaker    20   0  555768  38864  22688 S  95.6  0.2   0:00.31 mono ./lib/FsBeaker.exe 8804
  140 beaker    20   0  560204  39212  22828 S   0.0  0.2   0:00.31 mono ./lib/FsBeaker.exe 8804
  140 beaker    20   0  560204  39212  22828 S   0.0  0.2   0:00.31 mono ./lib/FsBeaker.exe 8804
  140 beaker    20   0  560204  39212  22828 S   0.0  0.2   0:00.31 mono ./lib/FsBeaker.exe 8804
  140 beaker    20   0  560204  39212  22828 S   0.0  0.2   0:00.31 mono ./lib/FsBeaker.exe 8804
  140 beaker    20   0  560204  39212  22828 S   0.0  0.2   0:00.31 mono ./lib/FsBeaker.exe 8804
  140 beaker    20   0  560204  39212  22828 S   0.0  0.2   0:00.31 mono ./lib/FsBeaker.exe 8804
  140 beaker    20   0  560204  39212  22828 S   0.0  0.2   0:00.31 mono ./lib/FsBeaker.exe 8804
  140 beaker    20   0  560204  39212  22828 S   0.0  0.2   0:00.31 mono ./lib/FsBeaker.exe 8804
  140 beaker    20   0  560204  39212  22828 S   0.0  0.2   0:00.31 mono ./lib/FsBeaker.exe 8804
  140 beaker    20   0  560204  39212  22828 S   0.0  0.2   0:00.31 mono ./lib/FsBeaker.exe 8804
  140 beaker    20   0  560204  39212  22828 S   0.0  0.2   0:00.31 mono ./lib/FsBeaker.exe 8804
```

**Comment by aolney** [comment]
This is resolved! It turns out to be a problem with the working directory. I'm not sure how to handle this in a cross platform way, however. [Documentation here](https://developer.xamarin.com/api/property/System.Diagnostics.ProcessStartInfo.UseShellExecute/) says that when UseShellExecute is false (as it **must** be to redirect stdi/o) then the working directory must be fully qualified.

I think the problem is that, when I run my test scripts, the executables and dlls are all being called from bin/Release, but when Beaker runs, it executes the fsharp plugin, which calls bin/fsharp, which calls lib/FsBeaker.exe. I'm guessing that the working directory is bin, when we actually want it to be lib.

I'm handling this right now with reflection:

```
    /// Starts a new instance of FsBeaker.Kernel.exe
    static member StartNewProcess() =
        let procStart = ProcessStartInfo()
        match Environment.OSVersion.Platform with
        | PlatformID.MacOSX | PlatformID.Unix ->
            procStart.FileName <- "mono"
            procStart.Arguments <- Path.Combine( Path.GetDirectoryName(System.Reflection.Assembly.GetExecutingAssembly().Location), "FsBeaker.Kernel.exe" )
        | _ -> procStart.FileName <- "FsBeaker.Kernel.exe"
        //
        procStart.RedirectStandardError <- true
        procStart.RedirectStandardInput <- true
        procStart.RedirectStandardOutput <- true
        procStart.UseShellExecute <- false
        procStart.CreateNoWindow <- true

        new ConsoleKernelClient(Process.Start(procStart))
```
